---
printWidth: 100
tabWidth: 4
useTabs: false
semi: true
singleQuote: true
trailingComma: none
bracketSpacing: true
jsxBracketSameLine: false
arrowParens: always
overrides:
  - files: ['*.yml', '*.yaml']
    options:
      tabWidth: 2
  - files: ['*.json']
    options:
      tabWidth: 2
