name: pull_request
on:
  pull_request:
    types: [opened, reopened, ready_for_review, synchronize, edited]

jobs:
  lint:
    name: ESLint
    runs-on: ubuntu-latest
    #if: !contains(github.event.pull_request.title , '[skip ci]')
    steps:
      - name: Checkout
        uses: actions/checkout@v1
      - name: Lint Check
        run: |
          yarn
          ./checks.sh lint
  test:
    name: Unit tests
    runs-on: ubuntu-latest
    #if: !contains(github.event.pull_request.title , '[skip ci]')
    steps:
      - name: Checkout
        uses: actions/checkout@v1
      - name: Test
        run: |
          yarn
          cd packages/react-date-primitives
          yarn test
  prettier:
    name: Prettier
    runs-on: ubuntu-latest
    #if: !contains(github.event.pull_request.title , '[skip ci]')
    steps:
      - name: Checkout
        uses: actions/checkout@v1
      - name: Prettier Check
        run: |
          yarn
          ./checks.sh prettier
